Add member Megan
Latina-Dev/latina-dev pull request #59
Opened 2023-06-06 20:11 UTC by amandhawb

## Overview

Adding one more Latina Dev! 😄 

## Relevant Issue

https://github.com/Latina-Dev/latina-dev/issues/57

> ✅️ By submitting this PR, I have verified the following

- [x] Reviewed the [contributing guidelines](https://github.com/Latina-Dev/latina-dev/blob/master/.github/CONTRIBUTING.md) 🔍️
- [x] Added my name to the bottom of the list under the **Contributors** section in the [README.md](https://github.com/Latina-Dev/latina-dev/blob/master/README.md) with a link to my personal website or GitHub profile 👥️

2023-06-09 16:33 UTC, FrancesCoronel commented
Otherwise looks good!

2023-06-12 18:26 UTC, EllaCodes4 commented
> Can we remove the change where the analytics component is moved slightly? It's not related and I think prettier would move it back anyways in next diff

Megan's photo looks stretched out on my end. @amandhawb: Can you resize to a 250px square and see if that looks better? The image is rectangular right now and I think that's why it. Thank you!

2023-06-13 12:34 UTC, amandhawb commented
> > Can we remove the change where the analytics component is moved slightly? It's not related and I think prettier would move it back anyways in next diff
> 
> Megan's photo looks stretched out on my end. @amandhawb: Can you resize to a 250px square and see if that looks better? The image is rectangular right now and I think that's why it. Thank you!

I resized it @EllaCodes4 , not sure if it changed because of the cache... I am still trying to see how to configure it

2023-06-13 23:38 UTC, FrancesCoronel requested changes

2023-06-13 23:38 UTC, FrancesCoronel commented on public/img/members/megan-rodriguez.jpg
you need to resize this image to be square (e.g. 250px by 250px)

2023-06-13 23:38 UTC, FrancesCoronel commented
> Can we remove the change where the analytics component is moved slightly? It's not related and I think prettier would move it back anyways in next diff

This was done, thank you! Just made two comments on the image + file name.

2023-06-15 19:05 UTC, EllaCodes4 commented on data/members/megan-rodriguez-.md
@amandhawb Yes, the photo cache has been temperamental. I wonder: Have you tried clearing the cache? If that doesn't work, maybe we should just delete Megan's profile and picture and try adding again!

2023-06-15 19:19 UTC, amandhawb commented on data/members/megan-rodriguez-.md
@EllaCodes4 I follow this https://stackoverflow.com/questions/68444505/how-to-clear-delete-cache-in-nextjs to clear the cache.. it doesn't change 😢 I will keep investigating, but if it took so long I will delete Megan's profile and add again as you suggested.

2023-06-16 19:47 UTC, FrancesCoronel commented
image is low res but otherwise looks good!

2023-06-16 19:47 UTC, FrancesCoronel approved these changes

2023-06-20 04:17 UTC, merged